server {
    listen 80 default_server;

    server_name _;

    location / {
        root /app/public;
        index index.html; # Явно укажите главный файл
    }

    location /api {
        proxy_pass http://localhost:8080;
    }
}